#!/bin/bash
# SLURM Subject-Level Connectivity Analysis Job Array Template
# This file serves as a reference for the template generated by hpc_submit_subject_level.py
# For actual job submission, use: python script/hpc_submit_subject_level.py [options]

#SBATCH --job-name=subject_level_connectivity
#SBATCH --array=1-44%20
#SBATCH --time=08:00:00
#SBATCH --mem=16G
#SBATCH --cpus-per-task=4
#SBATCH --partition=cpu-long
#SBATCH --output=logs/subject_level_%A_%a.out
#SBATCH --error=logs/subject_level_%A_%a.err

# ============================================================================
# Subject-Level Connectivity Analysis Pipeline
# Runs local measures, seed connectivity, and network connectivity
# for each subject-session pair
# ============================================================================

set -euo pipefail

# Configuration
REPO_ROOT="/home/clivewong/proj/longevity"
FMRIPREP_ROOT="${REPO_ROOT}/fmriprep"
OUTPUT_ROOT="results"
CONFIG_FILE=".github/connectivity_config.yaml"
LOG_DIR="logs"

# SLURM variables
ARRAY_ID=${SLURM_ARRAY_TASK_ID}
JOB_ID=${SLURM_ARRAY_JOB_ID}

# ============================================================================
# Helper Functions
# ============================================================================

log_info() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [INFO] $@" | tee -a "${LOG_FILE}"
}

log_error() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] [ERROR] $@" | tee -a "${LOG_FILE}"
}

fail_marker() {
    local subject=$1
    local session=$2
    local analysis=$3
    touch "${LOG_DIR}/.${subject}_${session}_${analysis}.failed"
}

success_marker() {
    local subject=$1
    local session=$2
    local analysis=$3
    rm -f "${LOG_DIR}/.${subject}_${session}_${analysis}.failed"
}

get_subject_from_index() {
    local idx=$1
    # Dynamically fetch subject from array index
    cd "${REPO_ROOT}"
    python3 -c "
import sys
sys.path.insert(0, 'script')
from hpc_submit_subject_level import SubjectLevelHPCSubmitter
submitter = SubjectLevelHPCSubmitter()
print(submitter._get_subject_from_index($idx))
"
}

# ============================================================================
# Main Execution
# ============================================================================

# Get subject ID for this array task
SUBJECT=$(get_subject_from_index $ARRAY_ID)
LOG_FILE="${LOG_DIR}/subject_level_${JOB_ID}_${ARRAY_ID}_${SUBJECT}.log"

log_info "Starting subject-level analysis for $SUBJECT (array task $ARRAY_ID/${SLURM_ARRAY_TASK_COUNT})"
log_info "Job ID: $JOB_ID | Array ID: $ARRAY_ID"

cd "$REPO_ROOT"

# Process both sessions
for SESSION in ses-01 ses-02; do
    log_info "Processing $SUBJECT $SESSION"
    
    # Find BOLD file (MNI space, 2mm resolution)
    BOLD_FILE=$(find "$FMRIPREP_ROOT" -name "${SUBJECT}_${SESSION}_*space-MNI152NLin2009cAsym*_desc-preproc_bold.nii.gz" | head -1)
    
    if [[ ! -f "$BOLD_FILE" ]]; then
        log_error "BOLD file not found for $SUBJECT $SESSION"
        continue
    fi
    
    # Find confounds file
    CONFOUNDS_FILE=$(find "$FMRIPREP_ROOT" -name "${SUBJECT}_${SESSION}_*desc-confounds_timeseries.tsv" | head -1)
    
    if [[ ! -f "$CONFOUNDS_FILE" ]]; then
        log_error "Confounds file not found for $SUBJECT $SESSION"
        continue
    fi
    
    log_info "BOLD: $BOLD_FILE"
    log_info "Confounds: $CONFOUNDS_FILE"
    
    # ========================================================================
    # 1. LOCAL MEASURES (fALFF, ReHo)
    # ========================================================================
    
    ANALYSIS="local_measures"
    LOCAL_OUTPUT="${OUTPUT_ROOT}/local_measures/${SUBJECT}_${SESSION}"
    
    log_info "Running $ANALYSIS for $SUBJECT $SESSION"
    
    if python3 script/compute_local_measures.py \
        --fmriprep "$FMRIPREP_ROOT" \
        --output "$LOCAL_OUTPUT" \
        --subjects "$SUBJECT" \
        --sessions "$SESSION" \
        --tr 0.8 \
        --low-freq 0.01 \
        --high-freq 0.1 \
        --config "$CONFIG_FILE" \
        >> "${LOG_FILE}" 2>&1; then
        
        log_info "$ANALYSIS completed successfully"
        success_marker "$SUBJECT" "$SESSION" "$ANALYSIS"
        
        # Record in manifest
        python3 script/hpc_manifest.py \
            --manifest "${OUTPUT_ROOT}/.manifest.json" \
            record \
            --subject "$SUBJECT" \
            --session "$SESSION" \
            --seed "N/A" \
            --atlas "N/A" \
            --status complete \
            --output "$LOCAL_OUTPUT" \
            --job-id "$JOB_ID" 2>&1 | tee -a "${LOG_FILE}" || true
    else
        log_error "$ANALYSIS failed"
        fail_marker "$SUBJECT" "$SESSION" "$ANALYSIS"
    fi
    
    # ========================================================================
    # 2. SEED-BASED CONNECTIVITY (all 17 seeds)
    # ========================================================================
    
    ANALYSIS="seed_connectivity"
    SEED_OUTPUT_BASE="${OUTPUT_ROOT}/seed_based"
    
    log_info "Running $ANALYSIS for $SUBJECT $SESSION"
    
    # Get seeds from config
    SEEDS=$(python3 -c "
import yaml
cfg = yaml.safe_load(open('$CONFIG_FILE'))
print(' '.join(cfg['seeds'].keys()))
")
    
    for SEED in $SEEDS; do
        for ATLAS in DiFuMo256 Schaefer400; do
            SEED_OUTPUT="${SEED_OUTPUT_BASE}/${ATLAS}/${SEED}/${SUBJECT}_${SESSION}"
            
            # Create output directory
            mkdir -p "$SEED_OUTPUT"
            
            # Note: This assumes seed_based_connectivity.py has been updated
            # to accept subject/session filters for job-array integration
            if python3 script/seed_based_connectivity.py \
                --fmriprep "$FMRIPREP_ROOT" \
                --bold "$BOLD_FILE" \
                --confounds "$CONFOUNDS_FILE" \
                --output "$SEED_OUTPUT" \
                --seed-name "$SEED" \
                --atlas "$ATLAS" \
                --tr 0.8 \
                --high-pass 0.01 \
                --low-pass 0.1 \
                >> "${LOG_FILE}" 2>&1; then
                
                log_info "Seed $SEED completed for $ATLAS"
                success_marker "$SUBJECT" "$SESSION" "$SEED"
                
                python3 script/hpc_manifest.py \
                    --manifest "${OUTPUT_ROOT}/.manifest.json" \
                    record \
                    --subject "$SUBJECT" \
                    --session "$SESSION" \
                    --seed "$SEED" \
                    --atlas "$ATLAS" \
                    --status complete \
                    --output "$SEED_OUTPUT" \
                    --job-id "$JOB_ID" 2>&1 | tee -a "${LOG_FILE}" || true
            else
                log_error "Seed $SEED failed for $ATLAS"
                fail_marker "$SUBJECT" "$SESSION" "$SEED"
            fi
        done
    done
    
    # ========================================================================
    # 3. NETWORK CONNECTIVITY (all atlases)
    # ========================================================================
    
    ANALYSIS="network_connectivity"
    
    log_info "Running $ANALYSIS for $SUBJECT $SESSION"
    
    for ATLAS in DiFuMo256 Schaefer400; do
        NETWORK_OUTPUT="${OUTPUT_ROOT}/network_connectivity/${ATLAS}/${SUBJECT}_${SESSION}"
        
        # Create output directory
        mkdir -p "$NETWORK_OUTPUT"
        
        if python3 script/compute_network_connectivity.py \
            --bold "$BOLD_FILE" \
            --confounds "$CONFOUNDS_FILE" \
            --output "$NETWORK_OUTPUT" \
            --atlas "$ATLAS" \
            --tr 0.8 \
            --high-pass 0.01 \
            --low-pass 0.1 \
            --smoothing 6.0 \
            >> "${LOG_FILE}" 2>&1; then
            
            log_info "Network connectivity completed for $ATLAS"
            success_marker "$SUBJECT" "$SESSION" "$ANALYSIS"
            
            python3 script/hpc_manifest.py \
                --manifest "${OUTPUT_ROOT}/.manifest.json" \
                record \
                --subject "$SUBJECT" \
                --session "$SESSION" \
                --seed "N/A" \
                --atlas "$ATLAS" \
                --status complete \
                --output "$NETWORK_OUTPUT" \
                --job-id "$JOB_ID" 2>&1 | tee -a "${LOG_FILE}" || true
        else
            log_error "Network connectivity failed for $ATLAS"
            fail_marker "$SUBJECT" "$SESSION" "$ANALYSIS"
        fi
    done
    
done

log_info "Completed all analyses for $SUBJECT"
