#!/bin/bash
#SBATCH --job-name={{JOB_NAME}}
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=12:00:00
#SBATCH --array=1-{{NUM_JOBS}}%10
#SBATCH --output=logs/group_level_%A_%a.out
#SBATCH --error=logs/group_level_%A_%a.err
#SBATCH --depend=afterok:{{SUBJECT_JOB_ID}}

# =============================================================================
# HPC SLURM Job Array Template: Group-Level Statistical Analysis
# =============================================================================
# Runs group-level connectivity analysis on HPC with:
# - Voxelwise linear mixed-effects (LME) modeling
# - Multiple comparison correction: {{CORRECTION_METHOD}} (GRF/TFCE/FDR)
# - Permutation testing ({{N_PERMUTATIONS}} permutations)
# - Anatomical cluster labeling with FSL atlasq
#
# Parallel job structure:
#   - Seed-based: Seeds × Atlases (17 seeds × 2 atlases = 34 jobs)
#   - Local measures: Atlases only (2 jobs)
#   - Network connectivity: 1 job
#   - Total: ~37 parallel jobs (max 10 concurrent)
#
# Dependency: Waits for subject-level jobs to complete ({{SUBJECT_JOB_ID}})
# =============================================================================

set -e

PROJECT_DIR="{{PROJECT_DIR}}"
SCRIPT_DIR="${PROJECT_DIR}/script"
RESULTS_ROOT="${PROJECT_DIR}/derivatives/connectivity-difumo256"
METADATA_FILE="${RESULTS_ROOT}/participants_all24_final.csv"
GROUP_OUTPUT_ROOT="${RESULTS_ROOT}/group-level"

TEST_MODE={{TEST_MODE}}
CORRECTION_METHOD="{{CORRECTION_METHOD}}"
N_PERMUTATIONS={{N_PERMUTATIONS}}

# Log setup
mkdir -p logs
exec 1> >(tee -a "logs/group_level_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.log")
exec 2>&1

echo "================================================================"
echo "Group-Level Statistical Analysis - SLURM Array Job"
echo "================================================================"
echo "Job ID: $SLURM_JOB_ID"
echo "Array Job ID: $SLURM_ARRAY_JOB_ID"
echo "Array Task ID: $SLURM_ARRAY_TASK_ID"
echo "Node: $SLURM_NODELIST"
echo "CPUs: $SLURM_CPUS_PER_TASK"
echo "Memory: 32GB"
echo "Start time: $(date)"
echo ""

# Activate conda environment on HPC
source "$HOME/miniconda3/etc/profile.d/conda.sh"
conda activate connectivity
cd "$PROJECT_DIR"

# =============================================================================
# JOB CONFIGURATION MAPPING
# =============================================================================
# Maps SLURM array task ID to analysis configuration.
# This must match the job map generated by hpc_submit_group_level.py

# Seed lists
SEEDS=(
    "anterior_insula"
    "dacc"
    "insula_dacc_combined"
    "hippocampus"
    "hippocampus_anterior"
    "hippocampus_posterior"
    "cerebellar_cognitive_l"
    "cerebellar_cognitive_r"
    "cerebellar_cognitive_bilateral"
    "cerebellar_motor"
    "cerebellar_vestibular"
    "motor_cortex"
    "default_mode"
    "frontoparietal_control"
    "dlpfc_l"
    "dlpfc_r"
    "dlpfc_bilateral"
)

ATLASES=(
    "DiFuMo256"
    "Schaefer400"
)

# Function to map array task to configuration
get_job_config() {
    local task_id=$1
    local num_seeds=${#SEEDS[@]}
    local num_atlases=${#ATLASES[@]}
    
    local seed_atlas_jobs=$((num_seeds * num_atlases))
    local local_measures_jobs=$num_atlases
    
    if [ "$task_id" -le "$seed_atlas_jobs" ]; then
        # Seed-based analysis
        local idx=$((task_id - 1))
        local seed_idx=$((idx / num_atlases))
        local atlas_idx=$((idx % num_atlases))
        
        ANALYSIS_TYPE="seed_based"
        SEED="${SEEDS[$seed_idx]}"
        ATLAS="${ATLASES[$atlas_idx]}"
    
    elif [ "$task_id" -le $((seed_atlas_jobs + local_measures_jobs)) ]; then
        # Local measures
        local idx=$((task_id - seed_atlas_jobs - 1))
        
        ANALYSIS_TYPE="local_measures"
        SEED=""
        ATLAS="${ATLASES[$idx]}"
    
    else
        # Network connectivity
        ANALYSIS_TYPE="network_connectivity"
        SEED=""
        ATLAS=""
    fi
}

# Map array task to configuration
get_job_config $SLURM_ARRAY_TASK_ID

echo "Analysis Type: $ANALYSIS_TYPE"
echo "Seed: ${SEED:-'N/A'}"
echo "Atlas: ${ATLAS:-'N/A'}"
echo ""

# =============================================================================
# EXECUTION: PER-ANALYSIS-TYPE LOGIC
# =============================================================================

if [ "$ANALYSIS_TYPE" = "seed_based" ]; then
    echo "=== SEED-BASED CONNECTIVITY ANALYSIS ==="
    
    # Input and output directories
    SEED_INPUT_ROOT="${RESULTS_ROOT}/subject-level/seed_based/${SEED}"
    OUTPUT_DIR="${GROUP_OUTPUT_ROOT}/seed_based/${ATLAS}/${SEED}"
    
    echo "Input: $SEED_INPUT_ROOT"
    echo "Output: $OUTPUT_DIR"
    echo ""
    
    if [ ! -d "$SEED_INPUT_ROOT" ]; then
        echo "ERROR: Input directory not found: $SEED_INPUT_ROOT"
        exit 1
    fi
    
    # Count z-maps
    zmap_count=$(find "$SEED_INPUT_ROOT" -name "*_zmap.nii.gz" 2>/dev/null | wc -l)
    echo "Found $zmap_count z-maps for $SEED"
    
    if [ "$zmap_count" -lt 40 ]; then
        echo "WARNING: Low z-map count. Expected >=48 (24 subjects × 2 sessions)"
    fi
    
    mkdir -p "$OUTPUT_DIR"
    
    # Run group-level seed analysis
    python "$SCRIPT_DIR/group_analysis_statistics.py" \
        --results "$RESULTS_ROOT" \
        --output "$OUTPUT_DIR" \
        --analysis-type seed_based \
        --atlas "$ATLAS" \
        --seed "$SEED" \
        --correction-method "$CORRECTION_METHOD" \
        --n-permutations "$N_PERMUTATIONS" \
        --log-level INFO
    
    # Label clusters with FSL atlasq
    if [ -f "$OUTPUT_DIR/cluster_table.csv" ]; then
        echo "Labeling clusters with anatomical atlas..."
        python "$SCRIPT_DIR/label_clusters_with_fsl_atlasq.py" \
            --cluster-table "$OUTPUT_DIR/cluster_table.csv" \
            --output "$OUTPUT_DIR/cluster_table_annotated.csv" \
            --atlas "$ATLAS" \
            || echo "WARNING: Cluster labeling failed (non-critical)"
    fi

elif [ "$ANALYSIS_TYPE" = "local_measures" ]; then
    echo "=== LOCAL MEASURES GROUP ANALYSIS ==="
    
    # Input and output directories
    LOCAL_MEASURES_INPUT_ROOT="${RESULTS_ROOT}/subject-level/local_measures"
    OUTPUT_DIR="${GROUP_OUTPUT_ROOT}/local_measures/${ATLAS}"
    
    echo "Input: $LOCAL_MEASURES_INPUT_ROOT"
    echo "Output: $OUTPUT_DIR"
    echo ""
    
    if [ ! -d "$LOCAL_MEASURES_INPUT_ROOT" ]; then
        echo "ERROR: Input directory not found: $LOCAL_MEASURES_INPUT_ROOT"
        exit 1
    fi
    
    mkdir -p "$OUTPUT_DIR"
    
    # Run group-level local measures analysis
    python "$SCRIPT_DIR/group_analysis_statistics.py" \
        --results "$RESULTS_ROOT" \
        --output "$OUTPUT_DIR" \
        --analysis-type local_measures \
        --atlas "$ATLAS" \
        --correction-method "$CORRECTION_METHOD" \
        --n-permutations "$N_PERMUTATIONS" \
        --log-level INFO

elif [ "$ANALYSIS_TYPE" = "network_connectivity" ]; then
    echo "=== NETWORK CONNECTIVITY GROUP ANALYSIS ==="
    
    # Input and output directories
    NETWORK_INPUT_ROOT="${RESULTS_ROOT}/subject-level/network_connectivity"
    OUTPUT_DIR="${GROUP_OUTPUT_ROOT}/network_connectivity"
    
    echo "Input: $NETWORK_INPUT_ROOT"
    echo "Output: $OUTPUT_DIR"
    echo ""
    
    if [ ! -d "$NETWORK_INPUT_ROOT" ]; then
        echo "ERROR: Input directory not found: $NETWORK_INPUT_ROOT"
        exit 1
    fi
    
    mkdir -p "$OUTPUT_DIR"
    
    # Run network connectivity group analysis
    python "$SCRIPT_DIR/group_analysis_statistics.py" \
        --results "$RESULTS_ROOT" \
        --output "$OUTPUT_DIR" \
        --analysis-type network_connectivity \
        --correction-method "$CORRECTION_METHOD" \
        --n-permutations "$N_PERMUTATIONS" \
        --log-level INFO
fi

# =============================================================================
# COMPLETION & REPORTING
# =============================================================================

echo ""
echo "================================================================"
echo "Analysis Complete for: $ANALYSIS_TYPE"
echo "End time: $(date)"
echo "================================================================"

# Check if output files were generated
if [ "$ANALYSIS_TYPE" = "seed_based" ]; then
    if [ -f "$OUTPUT_DIR/tstat_map.nii.gz" ]; then
        echo "SUCCESS: Output files generated"
        ls -lh "$OUTPUT_DIR" | head -10
        
        # Report cluster statistics
        if [ -f "$OUTPUT_DIR/cluster_table_annotated.csv" ]; then
            n_clusters=$(tail -n +2 "$OUTPUT_DIR/cluster_table_annotated.csv" | wc -l)
            echo "Significant clusters: $n_clusters"
        fi
    else
        echo "WARNING: Output files not generated. Check error logs."
        exit 1
    fi
elif [ "$ANALYSIS_TYPE" = "local_measures" ]; then
    if [ -f "$OUTPUT_DIR/fALFF_tstat_map.nii.gz" ] || [ -f "$OUTPUT_DIR/ReHo_tstat_map.nii.gz" ]; then
        echo "SUCCESS: Output files generated"
        ls -lh "$OUTPUT_DIR" | head -10
    else
        echo "WARNING: Output files not generated. Check error logs."
        exit 1
    fi
elif [ "$ANALYSIS_TYPE" = "network_connectivity" ]; then
    if [ -f "$OUTPUT_DIR/network_stats.json" ]; then
        echo "SUCCESS: Output files generated"
        ls -lh "$OUTPUT_DIR" | head -10
    else
        echo "WARNING: Output files not generated. Check error logs."
        exit 1
    fi
fi

echo "Job completed successfully"
exit 0
