"""
Dedicated XCP-D QC reports page — QC metrics plus HTML report viewer.
"""

from __future__ import annotations

from pathlib import Path
import sys
from typing import Optional

import streamlit as st
import streamlit.components.v1 as components

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from utils.pipeline_state import load_pipeline_state
from utils.xcpd_qc import render_xcpd_qc_reports


def _find_xcpd_session_reports(xcpd_dir: Path) -> dict[str, Path]:
    """Return {label: path} for all per-session HTML reports in an XCP-D output dir.

    The main session report lives at ``<xcpd_dir>/sub-XXX/ses-YY/sub-XXX_ses-YY.html``.
    """
    reports: dict[str, Path] = {}
    if not xcpd_dir.exists():
        return reports
    for html_path in sorted(xcpd_dir.glob("sub-*/ses-*/sub-*_ses-*.html")):
        # Use relative path as label, e.g. "sub-033/ses-01"
        parts = html_path.parts
        try:
            sub_part = parts[-3]  # sub-033
            ses_part = parts[-2]  # ses-01
            label = f"{sub_part} / {ses_part}"
        except IndexError:
            label = html_path.stem
        reports[label] = html_path
    return reports


def _render_report_viewer(pipeline_label: str, xcpd_dir: Path) -> None:
    """Embed XCP-D session HTML reports with a dropdown + prev/next navigator."""
    reports = _find_xcpd_session_reports(xcpd_dir)
    if not reports:
        st.info(f"No session HTML reports found in `{xcpd_dir}`.")
        return

    labels = list(reports.keys())
    state_key = f"xcpd_report_idx_{pipeline_label}"
    if state_key not in st.session_state:
        st.session_state[state_key] = 0

    nav_col1, nav_col2, nav_col3 = st.columns([1, 4, 1])
    with nav_col1:
        if st.button("⬅ Prev", key=f"prev_{pipeline_label}", disabled=st.session_state[state_key] == 0):
            st.session_state[state_key] -= 1
            st.rerun()
    with nav_col2:
        chosen = st.selectbox(
            "Session",
            options=labels,
            index=st.session_state[state_key],
            label_visibility="collapsed",
            key=f"sel_{pipeline_label}",
        )
        if chosen != labels[st.session_state[state_key]]:
            st.session_state[state_key] = labels.index(chosen)
            st.rerun()
    with nav_col3:
        if st.button("Next ➡", key=f"next_{pipeline_label}", disabled=st.session_state[state_key] == len(labels) - 1):
            st.session_state[state_key] += 1
            st.rerun()

    selected_label = labels[st.session_state[state_key]]
    html_path = reports[selected_label]
    st.caption(f"Showing: `{html_path}` ({len(labels)} sessions found)")
    try:
        html_content = html_path.read_text(encoding="utf-8", errors="replace")
        components.html(html_content, height=900, scrolling=True)
    except Exception as exc:
        st.error(f"Failed to load report: {exc}")


def render() -> None:
    config = st.session_state.get("config", {})
    if not config:
        st.error("Configuration not loaded.")
        return

    state = load_pipeline_state(config)
    paths = config.get("paths", {})

    tab_qc, tab_reports = st.tabs(["📈 QC Metrics", "📄 HTML Reports"])

    with tab_qc:
        render_xcpd_qc_reports(config, state, title="📊 XCP-D QC Reports")

    with tab_reports:
        st.subheader("XCP-D Session Reports")
        st.caption(
            "Inline viewer for the per-session HTML reports generated by XCP-D. "
            "Select a pipeline tab, then navigate through sessions using the dropdown or ◀ ▶ buttons."
        )

        r_fc, r_fc_gsr, r_ec = st.tabs(["FC", "FC+GSR", "EC"])
        pipeline_dirs = {
            "fc": Path(paths.get("xcpd_fc_dir", "")),
            "fc_gsr": Path(paths.get("xcpd_fc_gsr_dir", "")),
            "ec": Path(paths.get("xcpd_ec_dir", "")),
        }
        with r_fc:
            _render_report_viewer("fc", pipeline_dirs["fc"])
        with r_fc_gsr:
            _render_report_viewer("fc_gsr", pipeline_dirs["fc_gsr"])
        with r_ec:
            _render_report_viewer("ec", pipeline_dirs["ec"])


if __name__ == "__main__":
    render()
