"""
Dedicated XCP-D QC reports page — QC metrics plus HTML report viewer.
"""

from __future__ import annotations

from pathlib import Path
import sys
from typing import Optional

import streamlit as st
import streamlit.components.v1 as components

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from utils.pipeline_state import load_pipeline_state
from utils.xcpd_qc import render_xcpd_qc_reports


def _find_xcpd_session_reports(xcpd_dir: Path) -> dict[str, Path]:
    """Return {label: path} for all per-session HTML reports in an XCP-D output dir.

    XCP-D generates several HTML report types.  We search for:
    - ``**/*_desc-about_bold.html``   (executive summary, one per session)
    - ``**/*_desc-summary_bold.html`` (QC summary, one per session)
    - ``sub-*/ses-*/sub-*_ses-*.html``  (legacy/alternate session report pattern)

    The first match per subject/session is used as the representative report.
    """
    reports: dict[str, Path] = {}
    if not xcpd_dir.exists():
        return reports

    # Prefer the executive/summary reports generated by XCP-D
    for pattern in (
        "**/*_desc-about_bold.html",
        "**/*_desc-summary_bold.html",
        "sub-*/ses-*/sub-*_ses-*.html",
    ):
        for html_path in sorted(xcpd_dir.glob(pattern)):
            parts = html_path.parts
            # Derive a "sub-XXX / ses-YY" label from path components
            sub_part = next((p for p in parts if p.startswith("sub-")), None)
            ses_part = next((p for p in parts if p.startswith("ses-")), None)
            if sub_part and ses_part:
                label = f"{sub_part} / {ses_part}"
            else:
                label = html_path.stem
            # Don't overwrite a higher-priority match already added
            if label not in reports:
                reports[label] = html_path

    return reports


def _render_report_viewer(pipeline_label: str, xcpd_dir: Path | None) -> None:
    """Embed XCP-D session HTML reports with a dropdown + prev/next navigator."""
    if xcpd_dir is None:
        st.info(f"XCP-D output directory not configured for **{pipeline_label}** pipeline.")
        return

    reports = _find_xcpd_session_reports(xcpd_dir)
    if not reports:
        st.info(f"No session HTML reports found in `{xcpd_dir}`.")
        return

    labels = list(reports.keys())
    state_key = f"xcpd_report_idx_{pipeline_label}"
    if state_key not in st.session_state:
        st.session_state[state_key] = 0

    nav_col1, nav_col2, nav_col3 = st.columns([1, 4, 1])
    with nav_col1:
        if st.button("⬅ Prev", key=f"prev_{pipeline_label}", disabled=st.session_state[state_key] == 0):
            st.session_state[state_key] -= 1
            st.rerun()
    with nav_col2:
        chosen = st.selectbox(
            "Session",
            options=labels,
            index=st.session_state[state_key],
            label_visibility="collapsed",
            key=f"sel_{pipeline_label}",
        )
        if chosen != labels[st.session_state[state_key]]:
            st.session_state[state_key] = labels.index(chosen)
            st.rerun()
    with nav_col3:
        if st.button("Next ➡", key=f"next_{pipeline_label}", disabled=st.session_state[state_key] == len(labels) - 1):
            st.session_state[state_key] += 1
            st.rerun()

    selected_label = labels[st.session_state[state_key]]
    html_path = reports[selected_label]
    st.caption(f"Showing: `{html_path}` ({len(labels)} sessions found)")
    try:
        html_content = html_path.read_text(encoding="utf-8", errors="replace")
        components.html(html_content, height=900, scrolling=True)
    except Exception as exc:
        st.error(f"Failed to load report: {exc}")


def render() -> None:
    config = st.session_state.get("config", {})
    if not config:
        st.error("Configuration not loaded.")
        return

    state = load_pipeline_state(config)
    paths = config.get("paths", {})

    tab_qc, tab_reports = st.tabs(["📈 QC Metrics", "📄 HTML Reports"])

    with tab_qc:
        render_xcpd_qc_reports(config, state, title="📊 XCP-D QC Reports")

    with tab_reports:
        st.subheader("XCP-D Session Reports")
        st.caption(
            "Inline viewer for the per-session HTML reports generated by XCP-D. "
            "Select a pipeline tab, then navigate through sessions using the dropdown or ◀ ▶ buttons."
        )

        r_fc, r_fc_gsr, r_ec = st.tabs(["FC", "FC+GSR", "EC"])

        def _pipeline_path(key: str) -> Path | None:
            raw = paths.get(key, "")
            return Path(raw) if raw else None

        pipeline_dirs = {
            "fc": _pipeline_path("xcpd_fc_dir"),
            "fc_gsr": _pipeline_path("xcpd_fc_gsr_dir"),
            "ec": _pipeline_path("xcpd_ec_dir"),
        }
        with r_fc:
            _render_report_viewer("fc", pipeline_dirs["fc"])
        with r_fc_gsr:
            _render_report_viewer("fc_gsr", pipeline_dirs["fc_gsr"])
        with r_ec:
            _render_report_viewer("ec", pipeline_dirs["ec"])


if __name__ == "__main__":
    render()
